package com.bruce.chatui;

import android.content.Context;
import android.graphics.drawable.Drawable;

import java.util.HashMap;
import java.util.Map;

/**
 * 表情
 */
public class EmojiSmiley {

	private static HashMap<String, Emoji> map = new HashMap<String, Emoji>();
	
	static {
		map.put(":)", Emoji.fromResource(R.drawable.emoji_124, "[emts]_sys_0001_\r\n微笑\r\n:)[/emts]", false,1,"[:)]",Emoji.EMOJI_SMILEY));
		map.put(":D", Emoji.fromResource(R.drawable.emoji_00, "[emts]_sys_0002_\r\n开怀笑\r\n:D[/emts]", false,2,"[:D]",Emoji.EMOJI_SMILEY));
		map.put(";)", Emoji.fromResource(R.drawable.emoji_164, "[emts]_sys_0003_\r\n眨眼\r\n;)[/emts]", false,3,"[;)]",Emoji.EMOJI_SMILEY));
		map.put(":O", Emoji.fromResource(R.drawable.emoji_14, "[emts]_sys_0004_\r\n惊讶\r\n:O[/emts]", false,4,"[:O]",Emoji.EMOJI_SMILEY));
		map.put(":P", Emoji.fromResource(R.drawable.emoji_08, "[emts]_sys_0005_\r\n吐舌笑脸\r\n:P[/emts]", false,5,"[:P]",Emoji.EMOJI_SMILEY));
		map.put(":}", Emoji.fromResource(R.drawable.emoji_08, "[emts]_sys_0006_\r\n得意的笑\r\n:}[/emts]", true,6,"[:}]",Emoji.EMOJI_SMILEY));
		map.put(":@", Emoji.fromResource(R.drawable.emoji_20, "[emts]_sys_0007_\r\n生气\r\n:@[/emts]", false,7,"[:@]",Emoji.EMOJI_SMILEY));
		map.put(":S", Emoji.fromResource(R.drawable.emoji_12, "[emts]_sys_0008_\r\n怕怕\r\n:S[/emts]", false,8,"[:S]",Emoji.EMOJI_SMILEY));
		map.put(":$", Emoji.fromResource(R.drawable.emoji_09, "[emts]_sys_0009_\r\n尴尬\r\n:$[/emts]", false,9,"[:$]",Emoji.EMOJI_SMILEY));
		map.put(":(", Emoji.fromResource(R.drawable.emoji_16, "[emts]_sys_0010_\r\n难过\r\n:([/emts]", false,10,"[:(]",Emoji.EMOJI_SMILEY));
		map.put(":'(", Emoji.fromResource(R.drawable.emoji_17, "[emts]_sys_0011_\r\n哭泣\r\n:'([/emts]", false,11,"[:'(]",Emoji.EMOJI_SMILEY));
		map.put(":|", Emoji.fromResource(R.drawable.emoji_05, "[emts]_sys_0012_\r\n失望\r\n:|[/emts]", false,12,"[:|]",Emoji.EMOJI_SMILEY));
		map.put("(Z)", Emoji.fromResource(R.drawable.emoji_26, "[emts]_sys_0013_\r\n困了\r\n(Z)[/emts]", false,13,"[(Z)]",Emoji.EMOJI_SMILEY));
		map.put(":B", Emoji.fromResource(R.drawable.emoji_07, "[emts]_sys_0014_\r\n好好笑\r\n:B[/emts]", true,14,"[:B]",Emoji.EMOJI_SMILEY));
		map.put("(BO)", Emoji.fromResource(R.drawable.emoji_04, "[emts]_sys_0015_\r\n啵\r\n(BO)[/emts]", false,15,"[(BO)]",Emoji.EMOJI_SMILEY));
		map.put("(R)", Emoji.fromResource(R.drawable.emoji_02, "[emts]_sys_0016_\r\n电到了\r\n(R)[/emts]", false,16,"[(R)]",Emoji.EMOJI_SMILEY));
		map.put(":Q", Emoji.fromResource(R.drawable.emoji_145, "[emts]_sys_0017_\r\n汗\r\n:Q[/emts]", false,17,"[:Q]",Emoji.EMOJI_SMILEY));
		map.put("(!)", Emoji.fromResource(R.drawable.emoji_06, "[emts]_sys_0018_\r\n流口水了\r\n(!)[/emts]", false,18,"[(!)]",Emoji.EMOJI_SMILEY));
		map.put("(S)", Emoji.fromResource(R.drawable.emoji_162, "[emts]_sys_0019_\r\n真困啊\r\n(S)[/emts]", false,19,"[(S)]",Emoji.EMOJI_SMILEY));
		map.put("(V)", Emoji.fromResource(R.drawable.emoji_33, "[emts]_sys_0020_\r\n我吐\r\n(V)[/emts]", false,20,"[(V)]",Emoji.EMOJI_SMILEY));
		map.put("(?)", Emoji.fromResource(R.drawable.emoji_30, "[emts]_sys_0021_\r\n???\r\n(?)[/emts]", false,21,"[(?)]",Emoji.EMOJI_SMILEY));
		map.put("(X)", Emoji.fromResource(R.drawable.emoji_03, "[emts]_sys_0022_\r\n嘘...\r\n(X)[/emts]", false,22,"[(X)]",Emoji.EMOJI_SMILEY));
		map.put("(P)", Emoji.fromResource(R.drawable.emoji_13, "[emts]_sys_0023_\r\n砸死你\r\n(P)[/emts]", false,23,"[(P)]",Emoji.EMOJI_SMILEY));
		map.put("(-)", Emoji.fromResource(R.drawable.emoji_22, "[emts]_sys_0024_\r\n不说\r\n(-)[/emts]", false,24,"[(-)]",Emoji.EMOJI_SMILEY));
		map.put(":;", Emoji.fromResource(R.drawable.emoji_25, "[emts]_sys_0025_\r\n坏\r\n:;[/emts]", false,25,"[:;]",Emoji.EMOJI_SMILEY));
		map.put("(SS)", Emoji.fromResource(R.drawable.emoji_02, "[emts]_sys_0026_\r\n色迷迷\r\n(SS)[/emts]", true,26,"[(SS)]",Emoji.EMOJI_SMILEY));
		map.put("(@)", Emoji.fromResource(R.drawable.emoji_21, "[emts]_sys_0027_\r\n教训\r\n(@)[/emts]", true,27,"[(@)]",Emoji.EMOJI_SMILEY));
		map.put("(##)", Emoji.fromResource(R.drawable.emoji_01, "[emts]_sys_0028_\r\n可爱\r\n(##)[/emts]", false,28,"[(##)]",Emoji.EMOJI_SMILEY));
		map.put("(YY)", Emoji.fromResource(R.drawable.emoji_161, "[emts]_sys_0029_\r\nYEAH\r\n(YY)[/emts]", false,29,"[(YY)]",Emoji.EMOJI_SMILEY));
		map.put("(><)", Emoji.fromResource(R.drawable.emoji_31, "[emts]_sys_0030_\r\n崩溃\r\n(><)[/emts]", true, 30,"[(><)]",Emoji.EMOJI_SMILEY));
		map.put("(-.-)", Emoji.fromResource(R.drawable.emoji_23, "[emts]_sys_0031_\r\n鄙视你\r\n(-.-)[/emts]", false, 31,"[(-.-)]",Emoji.EMOJI_SMILEY));
		map.put("(~~)", Emoji.fromResource(R.drawable.emoji_07, "[emts]_sys_0032_\r\n开心\r\n(~~)[/emts]", false, 32,"[(~~)]",Emoji.EMOJI_SMILEY));
		map.put("(**)", Emoji.fromResource(R.drawable.emoji_163, "[emts]_sys_0033_\r\n仰慕你\r\n(**)[/emts]", false, 33,"[(**)]",Emoji.EMOJI_SMILEY));
		map.put("(@@)", Emoji.fromResource(R.drawable.emoji_32, "[emts]_sys_0034_\r\n晕\r\n(@@)[/emts]", false, 34,"[(@@)]",Emoji.EMOJI_SMILEY));
		map.put("(``)", Emoji.fromResource(R.drawable.emoji_29, "[emts]_sys_0035_\r\n挖鼻孔\r\n(``)[/emts]", false, 35,"[(``)]",Emoji.EMOJI_SMILEY));
		map.put("(%%)", Emoji.fromResource(R.drawable.emoji_08, "[emts]_sys_0036_\r\n撒娇\r\n(%%)[/emts]", true, 36,"[(%%)]",Emoji.EMOJI_SMILEY));
		map.put("(AA)", Emoji.fromResource(R.drawable.emoji_39, "[emts]_sys_0037_\r\n鼓掌\r\n(AA)[/emts]", false, 37,"[(AA)]",Emoji.EMOJI_SMILEY));
		map.put("(sy)", Emoji.fromResource(R.drawable.emoji_01, "[emts]_sys_0038_\r\n害羞\r\n(sy)[/emts]", true, 38,"[(sy)]",Emoji.EMOJI_SMILEY));
		map.put("(smo)", Emoji.fromResource(R.drawable.emoji_21, "[emts]_sys_0039_\r\n老大\r\n(smo)[/emts]", true,49,"[(smo)]",Emoji.EMOJI_SMILEY));
		map.put("(hit", Emoji.fromResource(R.drawable.emoji_31, "[emts]_sys_0040_\r\n欠揍\r\n(hit[/emts]", false,40,"[(hit]",Emoji.EMOJI_SMILEY));
		map.put("(kiss", Emoji.fromResource(R.drawable.emoji_166, "[emts]_sys_0041_\r\n飞吻\r\n(kiss[/emts]", true,41,"[(kiss]",Emoji.EMOJI_SMILEY));
		map.put("(busy", Emoji.fromResource(R.drawable.emoji_28, "[emts]_sys_0042_\r\n工作忙\r\n(busy[/emts]", false,42,"[(busy]",Emoji.EMOJI_SMILEY));
		map.put("(cry", Emoji.fromResource(R.drawable.emoji_18, "[emts]_sys_0043_\r\n大哭\r\n(cry[/emts]", false,43,"[(cry]",Emoji.EMOJI_SMILEY));
		map.put("(DD)", Emoji.fromResource(R.drawable.emoji_10, "[emts]_sys_0044_\r\n偷偷笑\r\n(DD)[/emts]", false,44,"[(DD)]",Emoji.EMOJI_SMILEY));
		map.put("(i$)", Emoji.fromResource(R.drawable.emoji_77, "[emts]_sys_0045_\r\n送花给你\r\n(i$)[/emts]", false,45,"[(i$)]",Emoji.EMOJI_SMILEY));
		map.put("(GK)", Emoji.fromResource(R.drawable.emoji_117, "[emts]_sys_0046_\r\n来，亲一个\r\n(GK)[/emts]", false,46,"[(GK)]",Emoji.EMOJI_SMILEY));
		map.put("(desk", Emoji.fromResource(R.drawable.emoji_31, "[emts]_sys_0047_\r\n拍桌子\r\n(desk[/emts]", false,47,"[(desk]",Emoji.EMOJI_SMILEY));
		map.put("(bye", Emoji.fromResource(R.drawable.emoji_166, "[emts]_sys_0048_\r\n拜拜\r\n(bye[/emts]", false,48,"[(bye]",Emoji.EMOJI_SMILEY));
		map.put("(ii)", Emoji.fromResource(R.drawable.emoji_164, "[emts]_sys_0049_\r\n飘阿飘\r\n(ii)[/emts]", true,65,"[(ii)]",Emoji.EMOJI_SMILEY));
		map.put("(xx)", Emoji.fromResource(R.drawable.emoji_11, "[emts]_sys_0050_\r\n秀一下\r\n(xx)[/emts]", false,57,"[(xx)]",Emoji.EMOJI_SMILEY));
		map.put("(fo)", Emoji.fromResource(R.drawable.emoji_25, "[emts]_sys_0051_\r\n阿弥陀佛\r\n(fo)[/emts]", false,59,"[(fo)]",Emoji.EMOJI_SMILEY));
		map.put("(^^)", Emoji.fromResource(R.drawable.emoji_01, "[emts]_sys_0052_\r\n无辜\r\n(^^)[/emts]", true,68,"[(^^)]",Emoji.EMOJI_SMILEY));
		map.put("(o.o)", Emoji.fromResource(R.drawable.emoji_19, "[emts]_sys_0053_\r\n抓狂\r\n(o.o)[/emts]", false,61,"[(o.o)]",Emoji.EMOJI_SMILEY));
		map.put("(--)", Emoji.fromResource(R.drawable.emoji_01, "[emts]_sys_0054_\r\n扭捏\r\n(--)[/emts]", true,58,"[(--)]",Emoji.EMOJI_SMILEY));
		map.put("(oo)", Emoji.fromResource(R.drawable.emoji_119, "[emts]_sys_0055_\r\n嗷嗷嗷\r\n(oo)[/emts]", false,56,"[(oo)]",Emoji.EMOJI_SMILEY));
		map.put("(/)", Emoji.fromResource(R.drawable.emoji_15, "[emts]_sys_0056_\r\n气呼呼\r\n(/)[/emts]", false,66,"[(/)]",Emoji.EMOJI_SMILEY));
		map.put("(,)", Emoji.fromResource(R.drawable.emoji_07, "[emts]_sys_0057_\r\n很得意\r\n(,)[/emts]", true,67,"[(,)]",Emoji.EMOJI_SMILEY));
		map.put("(G)", Emoji.fromResource(R.drawable.emoji_143, "[emts]_sys_0058_\r\n我是男生\r\n(G)[/emts]", false, 70,"[(G)]",Emoji.EMOJI_SMILEY));
		map.put("(M)", Emoji.fromResource(R.drawable.emoji_144, "[emts]_sys_0059_\r\n我是女生\r\n(M)[/emts]", false, 71,"[(M)]",Emoji.EMOJI_SMILEY));
		map.put("(F)", Emoji.fromResource(R.drawable.emoji_77, "[emts]_sys_0060_\r\n玫瑰\r\n(F)[/emts]", true,49,"[(F)]",Emoji.EMOJI_SMILEY));
		map.put("(L)", Emoji.fromResource(R.drawable.emoji_45, "[emts]_sys_0061_\r\n好爱你\r\n(L)[/emts]", false,50,"[(L)]",Emoji.EMOJI_SMILEY));
		map.put("(U)", Emoji.fromResource(R.drawable.emoji_46, "[emts]_sys_0062_\r\n心碎了\r\n(U)[/emts]", false,51,"[(U)]",Emoji.EMOJI_SMILEY));
		map.put("(K)", Emoji.fromResource(R.drawable.emoji_48, "[emts]_sys_0063_\r\n亲亲\r\n(K)[/emts]", false,69,"[(K)]",Emoji.EMOJI_SMILEY));
		map.put("(N)", Emoji.fromResource(R.drawable.emoji_35, "[emts]_sys_0064_\r\nNO\r\n(N)[/emts]", false, 53,"[(N)]",Emoji.EMOJI_SMILEY));
		map.put("(Y)", Emoji.fromResource(R.drawable.emoji_34, "[emts]_sys_0065_\r\nYES\r\n(Y)[/emts]", false, 52,"[(Y)]",Emoji.EMOJI_SMILEY));
		map.put("(H)", Emoji.fromResource(R.drawable.emoji_36, "[emts]_sys_0066_\r\n握个手\r\n(H)[/emts]", false, 54,"[(H)]",Emoji.EMOJI_SMILEY));
		map.put("(O)", Emoji.fromResource(R.drawable.emoji_44, "[emts]_sys_0067_\r\n到点了\r\n(O)[/emts]", false, 72,"[(O)]",Emoji.EMOJI_SMILEY));
		map.put("(music", Emoji.fromResource(R.drawable.emoji_106, "[emts]_sys_0068_\r\n音乐\r\n(music[/emts]", false,73,"[(music]",Emoji.EMOJI_SMILEY));
		map.put("(T)", Emoji.fromResource(R.drawable.emoji_81, "[emts]_sys_0069_\r\nCALL我\r\n(T)[/emts]", false, 74,"[(T)]",Emoji.EMOJI_SMILEY));
		map.put("(kill", Emoji.fromResource(R.drawable.emoji_94, "[emts]_sys_0070_\r\n带血的刀\r\n(kill[/emts]", false,75,"[(kill]",Emoji.EMOJI_SMILEY));
		map.put("(O')", Emoji.fromResource(R.drawable.emoji_92, "[emts]_sys_0071_\r\n炸弹\r\n(O')[/emts]", false,76,"[(O')]",Emoji.EMOJI_SMILEY));
		map.put("(I)", Emoji.fromResource(R.drawable.emoji_89, "[emts]_sys_0072_\r\n有了\r\n(I)[/emts]", false, 77,"[(I)]",Emoji.EMOJI_SMILEY));
		map.put("(E)", Emoji.fromResource(R.drawable.emoji_166, "[emts]_sys_0073_\r\n好晚了\r\n(E)[/emts]", true, 78,"[(E)]",Emoji.EMOJI_SMILEY));
		map.put(":[", Emoji.fromResource(R.drawable.emoji_141, "[emts]_sys_0074_\r\n吸血蝙蝠\r\n:[[/emts]", false,79,"[:[]",Emoji.EMOJI_SMILEY));
		map.put("(BB)", Emoji.fromResource(R.drawable.emoji_42, "[emts]_sys_0075_\r\n便便\r\n(BB)[/emts]", false, 80,"[(BB)]",Emoji.EMOJI_SMILEY));
		map.put("(D)", Emoji.fromResource(R.drawable.emoji_66, "[emts]_sys_0076_\r\n干一杯\r\n(D)[/emts]", false, 81,"[(D)]",Emoji.EMOJI_SMILEY));
		map.put("(SK)", Emoji.fromResource(R.drawable.emoji_91, "[emts]_sys_0077_\r\n抽烟\r\n(SK)[/emts]", false, 82,"[(SK)]",Emoji.EMOJI_SMILEY));
		map.put("(tel", Emoji.fromResource(R.drawable.emoji_82, "[emts]_sys_0078_\r\n打电话\r\n(tel[/emts]", false, 83,"[(tel]",Emoji.EMOJI_SMILEY));
		map.put("(home", Emoji.fromResource(R.drawable.emoji_113, "[emts]_sys_0079_\r\n家\r\n(home[/emts]", false, 84,"[(home]",Emoji.EMOJI_SMILEY));
		map.put("(car", Emoji.fromResource(R.drawable.emoji_112, "[emts]_sys_0080_\r\n车子\r\n(car[/emts]", false, 85,"[(car]",Emoji.EMOJI_SMILEY));
		map.put("(gift", Emoji.fromResource(R.drawable.emoji_142, "[emts]_sys_0081_\r\n礼物\r\n(gift[/emts]", false, 86,"[(gift]",Emoji.EMOJI_SMILEY));
		map.put("($)", Emoji.fromResource(R.drawable.emoji_97, "[emts]_sys_0082_\r\n金钱\r\n($)[/emts]", false, 87,"[($)]",Emoji.EMOJI_SMILEY));
		map.put("(sun", Emoji.fromResource(R.drawable.emoji_51, "[emts]_sys_0083_\r\n太阳\r\n(sun[/emts]", false, 88,"[(sun]",Emoji.EMOJI_SMILEY));
		map.put("(rain", Emoji.fromResource(R.drawable.emoji_55, "[emts]_sys_0084_\r\n下雨\r\n(rain[/emts]", false, 89,"[(rain]",Emoji.EMOJI_SMILEY));
		map.put("(W)", Emoji.fromResource(R.drawable.emoji_135, "[emts]_sys_0085_\r\n猪猪\r\n(W)[/emts]", false, 90,"[(W)]",Emoji.EMOJI_SMILEY));
		map.put("(cat", Emoji.fromResource(R.drawable.emoji_136, "[emts]_sys_0086_\r\n小猫\r\n(cat[/emts]", false, 91,"[(cat]",Emoji.EMOJI_SMILEY));
		map.put("(dog", Emoji.fromResource(R.drawable.emoji_133, "[emts]_sys_0087_\r\n小狗\r\n(dog[/emts]", false, 92,"[(dog]",Emoji.EMOJI_SMILEY));
		map.put("(8)", Emoji.fromResource(R.drawable.emoji_71, "[emts]_sys_0088_\r\n骨头\r\n(8)[/emts]", false, 93,"[(8)]",Emoji.EMOJI_SMILEY));
		map.put("(C)", Emoji.fromResource(R.drawable.emoji_65, "[emts]_sys_0089_\r\n喝水\r\n(C)[/emts]", false, 94,"[(C)]",Emoji.EMOJI_SMILEY));
		map.put("(HB)", Emoji.fromResource(R.drawable.emoji_70, "[emts]_sys_0090_\r\n汉堡\r\n(HB)[/emts]", false, 95,"[(HB)]",Emoji.EMOJI_SMILEY));
		map.put("(BZ)", Emoji.fromResource(R.drawable.emoji_70, "[emts]_sys_0091_\r\n包子\r\n(BZ)[/emts]", true, 96,"[(BZ)]",Emoji.EMOJI_SMILEY));
		map.put("(XG)", Emoji.fromResource(R.drawable.emoji_79, "[emts]_sys_0092_\r\n西瓜\r\n(XG)[/emts]", false, 97,"[(XG)]",Emoji.EMOJI_SMILEY));
		map.put("(YI)", Emoji.fromResource(R.drawable.emoji_68, "[emts]_sys_0093_\r\n约会\r\n(YI)[/emts]", false, 98,"[(YI)]",Emoji.EMOJI_SMILEY));
		map.put("(sigh", Emoji.fromResource(R.drawable.emoji_120, "[emts]_sys_0094_\r\n叹气\r\n(sigh[/emts]", false, 64,"[(sigh]",Emoji.EMOJI_SMILEY));
		map.put("(`3`)", Emoji.fromResource(R.drawable.emoji_117, "[emts]_sys_0095_\r\n啾啾\r\n(`3`)[/emts]", true, 62,"[(`3`)]",Emoji.EMOJI_SMILEY));
		map.put("(vo)", Emoji.fromResource(R.drawable.emoji_21, "[emts]_sys_0096_\r\n耍酷\r\n(vo)[/emts]", false, 63,"[(vo)]",Emoji.EMOJI_SMILEY));
		map.put("(mo)", Emoji.fromResource(R.drawable.emoji_163, "[emts]_sys_0097_\r\n摸摸\r\n(mo)[/emts]", true, 60,"[(mo)]",Emoji.EMOJI_SMILEY));
		map.put("(88)", Emoji.fromResource(R.drawable.emoji_163, "[emts]_sys_0098_\r\n睫毛弯弯\r\n(88)[/emts]", true, 55,"[(88)]",Emoji.EMOJI_SMILEY));
		map.put("#000", Emoji.fromResource(R.drawable.emotions_xiyou_000, "[emts]_xiyou_0001_\r\n微笑\r\n#000[/emts]", false,1,"[#000]",Emoji.EMOJI_GAME));
		map.put("#001", Emoji.fromResource(R.drawable.emotions_xiyou_001, "[emts]_xiyou_0002_\r\n笑\r\n#001[/emts]", false,2,"[#001]",Emoji.EMOJI_GAME));
		map.put("#002", Emoji.fromResource(R.drawable.emotions_xiyou_002, "[emts]_xiyou_0003_\r\n眨眼\r\n#002[/emts]", false,3,"[#002]",Emoji.EMOJI_GAME));
		map.put("#003", Emoji.fromResource(R.drawable.emotions_xiyou_003, "[emts]_xiyou_0004_\r\n晕\r\n#003[/emts]", false,4,"[#003]",Emoji.EMOJI_GAME));
		map.put("#004", Emoji.fromResource(R.drawable.emotions_xiyou_004, "[emts]_xiyou_0005_\r\n找死\r\n#004[/emts]", false,5,"[#004]",Emoji.EMOJI_GAME));
		map.put("#005", Emoji.fromResource(R.drawable.emotions_xiyou_005, "[emts]_xiyou_0006_\r\n飞喽\r\n#005[/emts]", false,6,"[#005]",Emoji.EMOJI_GAME));
		map.put("#006", Emoji.fromResource(R.drawable.emotions_xiyou_006, "[emts]_xiyou_0007_\r\n来杯饮料\r\n#006[/emts]", false,7,"[#006]",Emoji.EMOJI_GAME));
		map.put("#007", Emoji.fromResource(R.drawable.emotions_xiyou_007, "[emts]_xiyou_0008_\r\n咬你\r\n#007[/emts]", false,8,"[#007]",Emoji.EMOJI_GAME));
		map.put("#008", Emoji.fromResource(R.drawable.emotions_xiyou_008, "[emts]_xiyou_0009_\r\n心碎了\r\n#008[/emts]", false,9,"[#008]",Emoji.EMOJI_GAME));
		map.put("#009", Emoji.fromResource(R.drawable.emotions_xiyou_009, "[emts]_xiyou_0010_\r\n心\r\n#009[/emts]", false,10,"[#009]",Emoji.EMOJI_GAME));
		map.put("#010", Emoji.fromResource(R.drawable.emotions_xiyou_010, "[emts]_xiyou_0011_\r\n生日快乐\r\n#010[/emts]", false,11,"[#010]",Emoji.EMOJI_GAME));
		map.put("#011", Emoji.fromResource(R.drawable.emotions_xiyou_011, "[emts]_xiyou_0012_\r\n谢谢\r\n#011[/emts]", false,12,"[#011]",Emoji.EMOJI_GAME));
		map.put("#012", Emoji.fromResource(R.drawable.emotions_xiyou_012, "[emts]_xiyou_0013_\r\n到点了\r\n#012[/emts]", false,13,"[#012]",Emoji.EMOJI_GAME));
		map.put("#013", Emoji.fromResource(R.drawable.emotions_xiyou_013, "[emts]_xiyou_0014_\r\n休息一下\r\n#013[/emts]", false,14,"[#013]",Emoji.EMOJI_GAME));
		map.put("#014", Emoji.fromResource(R.drawable.emotions_xiyou_014, "[emts]_xiyou_0015_\r\n发愁\r\n#014[/emts]", false,15,"[#014]",Emoji.EMOJI_GAME));
		map.put("#015", Emoji.fromResource(R.drawable.emotions_xiyou_015, "[emts]_xiyou_0016_\r\n大哭\r\n#015[/emts]", false,16,"[#015]",Emoji.EMOJI_GAME));
		map.put("#016", Emoji.fromResource(R.drawable.emotions_xiyou_016, "[emts]_xiyou_0017_\r\n我是小恶魔\r\n#016[/emts]", false,17,"[#016]",Emoji.EMOJI_GAME));
		map.put("#017", Emoji.fromResource(R.drawable.emotions_xiyou_017, "[emts]_xiyou_0018_\r\n害羞\r\n#017[/emts]", false,18,"[#017]",Emoji.EMOJI_GAME));
		map.put("#018", Emoji.fromResource(R.drawable.emotions_xiyou_018, "[emts]_xiyou_0019_\r\n得意的笑\r\n#018[/emts]", false,19,"[#018]",Emoji.EMOJI_GAME));
		map.put("#019", Emoji.fromResource(R.drawable.emotions_xiyou_019, "[emts]_xiyou_0020_\r\n我是MM\r\n#019[/emts]", false,20,"[#019]",Emoji.EMOJI_GAME));
		map.put("#020", Emoji.fromResource(R.drawable.emotions_xiyou_020, "[emts]_xiyou_0021_\r\n我是GG\r\n#020[/emts]", false,21,"[#020]",Emoji.EMOJI_GAME));
		map.put("#021", Emoji.fromResource(R.drawable.emotions_xiyou_021, "[emts]_xiyou_0022_\r\n嘴一个\r\n#021[/emts]", false,22,"[#021]",Emoji.EMOJI_GAME));
		map.put("#022", Emoji.fromResource(R.drawable.emotions_xiyou_022, "[emts]_xiyou_0023_\r\n电话联系\r\n#022[/emts]", false,23,"[#022]",Emoji.EMOJI_GAME));
		map.put("#023", Emoji.fromResource(R.drawable.emotions_xiyou_023, "[emts]_xiyou_0024_\r\n送花给你\r\n#023[/emts]", false,24,"[#023]",Emoji.EMOJI_GAME));
		map.put("#024", Emoji.fromResource(R.drawable.emotions_xiyou_024, "[emts]_xiyou_0025_\r\n惊讶\r\n#024[/emts]", false,25,"[#024]",Emoji.EMOJI_GAME));
		map.put("#025", Emoji.fromResource(R.drawable.emotions_xiyou_025, "[emts]_xiyou_0026_\r\n吐舌头\r\n#025[/emts]", false,26,"[#025]",Emoji.EMOJI_GAME));
		map.put("#026", Emoji.fromResource(R.drawable.emotions_xiyou_026, "[emts]_xiyou_0027_\r\n强人\r\n#026[/emts]", false,27,"[#026]",Emoji.EMOJI_GAME));
		map.put("#027", Emoji.fromResource(R.drawable.emotions_xiyou_027, "[emts]_xiyou_0028_\r\n菜鸟\r\n#027[/emts]", false,28,"[#027]",Emoji.EMOJI_GAME));
		map.put("#028", Emoji.fromResource(R.drawable.emotions_xiyou_028, "[emts]_xiyou_0029_\r\n戴墨镜\r\n#028[/emts]", false,29,"[#028]",Emoji.EMOJI_GAME));
		map.put("#029", Emoji.fromResource(R.drawable.emotions_xiyou_029, "[emts]_xiyou_0030_\r\n猪\r\n#029[/emts]", false, 30,"[#029]",Emoji.EMOJI_GAME));
		map.put("#030", Emoji.fromResource(R.drawable.emotions_xiyou_030, "[emts]_xiyou_0031_\r\n注意\r\n#030[/emts]", false, 31,"[#030]",Emoji.EMOJI_GAME));
		map.put("#031", Emoji.fromResource(R.drawable.emotions_xiyou_031, "[emts]_xiyou_0032_\r\n来杯饮料\r\n#031[/emts]", false, 32,"[#031]",Emoji.EMOJI_GAME));
		map.put("#032", Emoji.fromResource(R.drawable.emotions_xiyou_032, "[emts]_xiyou_0033_\r\n喊话\r\n#032[/emts]", false, 33,"[#032]",Emoji.EMOJI_GAME));
		map.put("#033", Emoji.fromResource(R.drawable.emotions_xiyou_033, "[emts]_xiyou_0034_\r\n礼盒\r\n#033[/emts]", false, 34,"[#033]",Emoji.EMOJI_GAME));
		map.put("#034", Emoji.fromResource(R.drawable.emotions_xiyou_034, "[emts]_xiyou_0035_\r\n已经很晚了\r\n#034[/emts]", false, 35,"[#034]",Emoji.EMOJI_GAME));
		map.put("#035", Emoji.fromResource(R.drawable.emotions_xiyou_035, "[emts]_xiyou_0036_\r\n做什么\r\n#035[/emts]", false, 36,"[#035]",Emoji.EMOJI_GAME));
		map.put("#036", Emoji.fromResource(R.drawable.emotions_xiyou_036, "[emts]_xiyou_0037_\r\n有想法了\r\n#036[/emts]", false, 37,"[#036]",Emoji.EMOJI_GAME));
		map.put("#037", Emoji.fromResource(R.drawable.emotions_xiyou_037, "[emts]_xiyou_0038_\r\n我是小天使\r\n#037[/emts]", false, 38,"[#037]",Emoji.EMOJI_GAME));
		map.put("#038", Emoji.fromResource(R.drawable.emotions_xiyou_038, "[emts]_xiyou_0039_\r\n问候\r\n#038[/emts]", false,39,"[#038]",Emoji.EMOJI_GAME));
		map.put("#039", Emoji.fromResource(R.drawable.emotions_xiyou_039, "[emts]_xiyou_0040_\r\n扇扇子\r\n#039[/emts]", false,40,"[#039]",Emoji.EMOJI_GAME));
		map.put("#040", Emoji.fromResource(R.drawable.emotions_xiyou_040, "[emts]_xiyou_0041_\r\n擦汗\r\n#040[/emts]", true,41,"[#040]",Emoji.EMOJI_GAME));
		map.put("#041", Emoji.fromResource(R.drawable.emotions_xiyou_041, "[emts]_xiyou_0042_\r\n高兴\r\n#041[/emts]", false,42,"[#041]",Emoji.EMOJI_GAME));
		map.put("#042", Emoji.fromResource(R.drawable.emotions_xiyou_042, "[emts]_xiyou_0043_\r\n唱\r\n#042[/emts]", false,43,"[#042]",Emoji.EMOJI_GAME));
		map.put("#043", Emoji.fromResource(R.drawable.emotions_xiyou_043, "[emts]_xiyou_0044_\r\n快点\r\n#043[/emts]", false,44,"[#043]",Emoji.EMOJI_GAME));
		map.put("#044", Emoji.fromResource(R.drawable.emotions_xiyou_044, "[emts]_xiyou_0045_\r\n摇尾巴\r\n#044[/emts]", false,45,"[#044]",Emoji.EMOJI_GAME));
		map.put("#045", Emoji.fromResource(R.drawable.emotions_xiyou_045, "[emts]_xiyou_0046_\r\n怎么了？\r\n#045[/emts]", false,46,"[#045]",Emoji.EMOJI_GAME));
		map.put("#046", Emoji.fromResource(R.drawable.emotions_xiyou_046, "[emts]_xiyou_0047_\r\n喊话\r\n#046[/emts]", false,47,"[#046]",Emoji.EMOJI_GAME));
		map.put("#047", Emoji.fromResource(R.drawable.emotions_xiyou_047, "[emts]_xiyou_0048_\r\n撒娇\r\n#047[/emts]", false,48,"[#047]",Emoji.EMOJI_GAME));
		map.put("#048", Emoji.fromResource(R.drawable.emotions_xiyou_048, "[emts]_xiyou_0049_\r\n敲你头\r\n#048[/emts]", false,49,"[#048]",Emoji.EMOJI_GAME));
		map.put("#049", Emoji.fromResource(R.drawable.emotions_xiyou_049, "[emts]_xiyou_0050_\r\n胜利了\r\n#049[/emts]", false,50,"[#049]",Emoji.EMOJI_GAME));
		map.put("#050", Emoji.fromResource(R.drawable.emotions_xiyou_050, "[emts]_xiyou_0051_\r\n鼓掌\r\n#050[/emts]", false,51,"[#050]",Emoji.EMOJI_GAME));
		map.put("#051", Emoji.fromResource(R.drawable.emotions_xiyou_051, "[emts]_xiyou_0052_\r\n叫喊\r\n#051[/emts]", false,52,"[#051]",Emoji.EMOJI_GAME));
		map.put("#052", Emoji.fromResource(R.drawable.emotions_xiyou_052, "[emts]_xiyou_0053_\r\n哭\r\n#052[/emts]", false,53,"[#052]",Emoji.EMOJI_GAME));
		map.put("#053", Emoji.fromResource(R.drawable.emotions_xiyou_053, "[emts]_xiyou_0054_\r\n翻筋斗\r\n#053[/emts]", false,54,"[#053]",Emoji.EMOJI_GAME));
		map.put("#054", Emoji.fromResource(R.drawable.emotions_xiyou_054, "[emts]_xiyou_0055_\r\n生气\r\n#054[/emts]", false,55,"[#054]",Emoji.EMOJI_GAME));
		map.put("#055", Emoji.fromResource(R.drawable.emotions_xiyou_055, "[emts]_xiyou_0056_\r\n干什么\r\n#055[/emts]", false,56,"[#055]",Emoji.EMOJI_GAME));
		map.put("#056", Emoji.fromResource(R.drawable.emotions_xiyou_056, "[emts]_xiyou_0057_\r\n偷笑\r\n#056[/emts]", false,57,"[#056]",Emoji.EMOJI_GAME));
		map.put("#057", Emoji.fromResource(R.drawable.emotions_xiyou_057, "[emts]_xiyou_0058_\r\n有事M我\r\n#057[/emts]", false, 58,"[#057]",Emoji.EMOJI_GAME));
		map.put("#058", Emoji.fromResource(R.drawable.emotions_xiyou_058, "[emts]_xiyou_0059_\r\n嗯\r\n#058[/emts]", false, 59,"[#058]",Emoji.EMOJI_GAME));
		map.put("#059", Emoji.fromResource(R.drawable.emotions_xiyou_059, "[emts]_xiyou_0060_\r\n喝水\r\n#059[/emts]", false,60,"[#059]",Emoji.EMOJI_GAME));
		map.put("#060", Emoji.fromResource(R.drawable.emotions_xiyou_060, "[emts]_xiyou_0061_\r\n吐\r\n#060[/emts]", false,61,"[#060]",Emoji.EMOJI_GAME));
		map.put("#061", Emoji.fromResource(R.drawable.emotions_xiyou_061, "[emts]_xiyou_0062_\r\n太高兴啦\r\n#061[/emts]", false,62,"[#061]",Emoji.EMOJI_GAME));
		map.put("#062", Emoji.fromResource(R.drawable.emotions_xiyou_062, "[emts]_xiyou_0063_\r\n看我表演\r\n#062[/emts]", false,63,"[#062]",Emoji.EMOJI_GAME));
		map.put("#063", Emoji.fromResource(R.drawable.emotions_xiyou_063, "[emts]_xiyou_0064_\r\n被你吓到了\r\n#063[/emts]", false, 64,"[#063]",Emoji.EMOJI_GAME));
		map.put("#064", Emoji.fromResource(R.drawable.emotions_xiyou_064, "[emts]_xiyou_0065_\r\n兴高采烈\r\n#064[/emts]", false, 65,"[#064]",Emoji.EMOJI_GAME));
		map.put("#074", Emoji.fromResource(R.drawable.emotions_xiyou_074, "[emts]_xiyou_0066_\r\n吐\r\n#074[/emts]", false,66,"[#074]",Emoji.EMOJI_GAME));
		map.put("#075", Emoji.fromResource(R.drawable.emotions_xiyou_075, "[emts]_xiyou_0067_\r\n给你一锤子\r\n#075[/emts]", false, 67,"[#075]",Emoji.EMOJI_GAME));
		map.put("#076", Emoji.fromResource(R.drawable.emotions_xiyou_076, "[emts]_xiyou_0068_\r\n闭嘴\r\n#076[/emts]", false,68,"[#076]",Emoji.EMOJI_GAME));
		map.put("#077", Emoji.fromResource(R.drawable.emotions_xiyou_077, "[emts]_xiyou_0069_\r\n睡觉觉\r\n#077[/emts]", false,69,"[#077]",Emoji.EMOJI_GAME));
		map.put("#078", Emoji.fromResource(R.drawable.emotions_xiyou_078, "[emts]_xiyou_0070_\r\n无可奈何\r\n#078[/emts]", false, 70,"[#078]",Emoji.EMOJI_GAME));
		map.put("#079", Emoji.fromResource(R.drawable.emotions_xiyou_079, "[emts]_xiyou_0071_\r\n我是医生\r\n#079[/emts]", false, 71,"[#079]",Emoji.EMOJI_GAME));
		map.put("#080", Emoji.fromResource(R.drawable.emotions_xiyou_080, "[emts]_xiyou_0072_\r\n鄙视你\r\n#080[/emts]", false,72,"[#080]",Emoji.EMOJI_GAME));
		map.put("#081", Emoji.fromResource(R.drawable.emotions_xiyou_081, "[emts]_xiyou_0073_\r\n吃饭咯\r\n#081[/emts]", false, 73,"[#081]",Emoji.EMOJI_GAME));
		map.put("#082", Emoji.fromResource(R.drawable.emotions_xiyou_082, "[emts]_xiyou_0074_\r\n我回来了\r\n#082[/emts]", false, 74,"[#082]",Emoji.EMOJI_GAME));
		map.put("#083", Emoji.fromResource(R.drawable.emotions_xiyou_083, "[emts]_xiyou_0075_\r\n汗\r\n#083[/emts]", false, 75,"[#083]",Emoji.EMOJI_GAME));
		map.put("#084", Emoji.fromResource(R.drawable.emotions_xiyou_084, "[emts]_xiyou_0076_\r\n好厉害哦\r\n#084[/emts]", false, 76,"[#084]",Emoji.EMOJI_GAME));
		map.put("#085", Emoji.fromResource(R.drawable.emotions_xiyou_085, "[emts]_xiyou_0077_\r\n看我怎么收拾你\r\n#085[/emts]", false, 77,"[#085]",Emoji.EMOJI_GAME));
		map.put("#086", Emoji.fromResource(R.drawable.emotions_xiyou_086, "[emts]_xiyou_0078_\r\n开大餐咯\r\n#086[/emts]", false, 78,"[#086]",Emoji.EMOJI_GAME));
		map.put("#087", Emoji.fromResource(R.drawable.emotions_xiyou_087, "[emts]_xiyou_0079_\r\n不要啊\r\n#087[/emts]", false, 79,"[#087]",Emoji.EMOJI_GAME));
		map.put("#088", Emoji.fromResource(R.drawable.emotions_xiyou_088, "[emts]_xiyou_0080_\r\n顶\r\n#088[/emts]", false, 80,"[#088]",Emoji.EMOJI_GAME));
		map.put("#089", Emoji.fromResource(R.drawable.emotions_xiyou_089, "[emts]_xiyou_0081_\r\n流口水\r\n#089[/emts]", false, 81,"[#089]",Emoji.EMOJI_GAME));
		map.put("#090", Emoji.fromResource(R.drawable.emotions_xiyou_090, "[emts]_xiyou_0082_\r\n超人来啦\r\n#090[/emts]", false, 82,"[#090]",Emoji.EMOJI_GAME));
		map.put("#091", Emoji.fromResource(R.drawable.emotions_xiyou_091, "[emts]_xiyou_0083_\r\n不理你\r\n#091[/emts]", false, 83,"[#091]",Emoji.EMOJI_GAME));
		map.put("#092", Emoji.fromResource(R.drawable.emotions_xiyou_092, "[emts]_xiyou_0084_\r\nYea!\r\n#092[/emts]", false, 84,"[#092]",Emoji.EMOJI_GAME));
		map.put("#093", Emoji.fromResource(R.drawable.emotions_xiyou_093, "[emts]_xiyou_0085_\r\n加油\r\n#093[/emts]", false, 85,"[#093]",Emoji.EMOJI_GAME));
		map.put("#094", Emoji.fromResource(R.drawable.emotions_xiyou_094, "[emts]_xiyou_0086_\r\n有信件\r\n#094[/emts]", false, 86,"[#094]",Emoji.EMOJI_GAME));
		map.put("#095", Emoji.fromResource(R.drawable.emotions_xiyou_095, "[emts]_xiyou_0087_\r\n抽烟\r\n#095[/emts]", false, 87,"[#095]",Emoji.EMOJI_GAME));
		map.put("#096", Emoji.fromResource(R.drawable.emotions_xiyou_096, "[emts]_xiyou_0088_\r\n亲一个\r\n#096[/emts]", false, 88,"[#096]",Emoji.EMOJI_GAME));
		map.put("#097", Emoji.fromResource(R.drawable.emotions_xiyou_097, "[emts]_xiyou_0089_\r\n美女啊\r\n#097[/emts]", false, 89,"[#097]",Emoji.EMOJI_GAME));
		map.put("#098", Emoji.fromResource(R.drawable.emotions_xiyou_098, "[emts]_xiyou_0090_\r\n恩爱\r\n#098[/emts]", false, 90,"[#098]",Emoji.EMOJI_GAME));
		map.put("#099", Emoji.fromResource(R.drawable.emotions_xiyou_099, "[emts]_xiyou_0091_\r\n流鼻血\r\n#099[/emts]", false, 99,"[#099]",Emoji.EMOJI_GAME));
		map.put("#101", Emoji.fromResource(R.drawable.emotions_xiyou_101, "[emts]_xiyou_0092_\r\n强\r\n#101[/emts]", false, 101,"[#101]",Emoji.EMOJI_GAME));
		map.put("#102", Emoji.fromResource(R.drawable.emotions_xiyou_102, "[emts]_xiyou_0093_\r\n我醉啦\r\n#102[/emts]", false, 102,"[#102]",Emoji.EMOJI_GAME));
		map.put("#103", Emoji.fromResource(R.drawable.emotions_xiyou_103, "[emts]_xiyou_0094_\r\n送花给你！\r\n#103[/emts]", false, 103,"[#103]",Emoji.EMOJI_GAME));
		map.put("#104", Emoji.fromResource(R.drawable.emotions_xiyou_104, "[emts]_xiyou_0095_\r\n写信中…\r\n#104[/emts]", false, 104,"[#104]",Emoji.EMOJI_GAME));
		map.put("#105", Emoji.fromResource(R.drawable.emotions_xiyou_105, "[emts]_xiyou_0096_\r\n是他干的\r\n#105[/emts]", false, 105,"[#105]",Emoji.EMOJI_GAME));
		map.put("#106", Emoji.fromResource(R.drawable.emotions_xiyou_106, "[emts]_xiyou_0097_\r\n快来人啊\r\n#106[/emts]", false, 106,"[#106]",Emoji.EMOJI_GAME));
		map.put("#107", Emoji.fromResource(R.drawable.emotions_xiyou_107, "[emts]_xiyou_0098_\r\n好好高兴\r\n#107[/emts]", false, 107,"[#107]",Emoji.EMOJI_GAME));
		map.put("#108", Emoji.fromResource(R.drawable.emotions_xiyou_108, "[emts]_xiyou_0099_\r\n不见不散\r\n#108[/emts]", false, 108,"[#108]",Emoji.EMOJI_GAME));
		map.put("#109", Emoji.fromResource(R.drawable.emotions_xiyou_109, "[emts]_xiyou_0100_\r\n阿弥陀佛\r\n#109[/emts]", false, 109,"[#109]",Emoji.EMOJI_GAME));
		map.put("#110", Emoji.fromResource(R.drawable.emotions_xiyou_110, "[emts]_xiyou_0101_\r\n好温馨啊\r\n#110[/emts]", false, 110,"[#110]",Emoji.EMOJI_GAME));
		map.put("#111", Emoji.fromResource(R.drawable.emotions_xiyou_111, "[emts]_xiyou_0102_\r\n闪先\r\n#111[/emts]", false,111,"[#111]",Emoji.EMOJI_GAME));
		map.put("#112", Emoji.fromResource(R.drawable.emotions_xiyou_112, "[emts]_xiyou_0103_\r\n只有我最摇摆\r\n#112[/emts]", true, 112,"[#112]",Emoji.EMOJI_GAME));
		map.put("#113", Emoji.fromResource(R.drawable.emotions_xiyou_113, "[emts]_xiyou_0104_\r\n见鬼啦\r\n#113[/emts]", false, 113,"[#113]",Emoji.EMOJI_GAME));
		map.put("#114", Emoji.fromResource(R.drawable.emotions_xiyou_114, "[emts]_xiyou_0105_\r\n摸摸\r\n#114[/emts]", false, 114,"[#114]",Emoji.EMOJI_GAME));
		map.put("#115", Emoji.fromResource(R.drawable.emotions_xiyou_115, "[emts]_xiyou_0106_\r\n捏脸蛋\r\n#115[/emts]", true, 115,"[#115]",Emoji.EMOJI_GAME));
		map.put("#116", Emoji.fromResource(R.drawable.emotions_xiyou_116, "[emts]_xiyou_0107_\r\n悲剧\r\n#116[/emts]", false, 116,"[#116]",Emoji.EMOJI_GAME));
		map.put("#117", Emoji.fromResource(R.drawable.emotions_xiyou_117, "[emts]_xiyou_0108_\r\n拍马屁\r\n#117[/emts]", false, 117,"[#117]",Emoji.EMOJI_GAME));
		map.put("#118", Emoji.fromResource(R.drawable.emotions_xiyou_118, "[emts]_xiyou_0109_\r\n大汗\r\n#118[/emts]", false, 118,"[#118]",Emoji.EMOJI_GAME));
		map.put("#119", Emoji.fromResource(R.drawable.emotions_xiyou_119, "[emts]_xiyou_0110_\r\n掀桌子\r\n#119[/emts]", true, 119,"[#119]",Emoji.EMOJI_GAME));
		map.put("#120", Emoji.fromResource(R.drawable.emotions_xiyou_120, "[emts]_xiyou_0111_\r\n撞墙\r\n#120[/emts]", true, 120,"[#120]",Emoji.EMOJI_GAME));
		map.put("#121", Emoji.fromResource(R.drawable.emotions_xiyou_121, "[emts]_xiyou_0112_\r\n囧\r\n#121[/emts]", false, 121,"[#121]",Emoji.EMOJI_GAME));
		map.put("#122", Emoji.fromResource(R.drawable.emotions_xiyou_122, "[emts]_xiyou_0113_\r\n捏脸脸\r\n#122[/emts]", true, 122,"[#122]",Emoji.EMOJI_GAME));
		map.put("#123", Emoji.fromResource(R.drawable.emotions_xiyou_123, "[emts]_xiyou_0114_\r\n抱抱\r\n#123[/emts]", true, 123,"[#123]",Emoji.EMOJI_GAME));
		map.put("#124", Emoji.fromResource(R.drawable.emotions_xiyou_124, "[emts]_xiyou_0115_\r\n你在干嘛？！\r\n#124[/emts]", true, 124,"[#124]",Emoji.EMOJI_GAME));
		map.put("#125", Emoji.fromResource(R.drawable.emotions_xiyou_125, "[emts]_xiyou_0116_\r\n演讲\r\n#125[/emts]", false, 125,"[#125]",Emoji.EMOJI_GAME));
		map.put("#126", Emoji.fromResource(R.drawable.emotions_xiyou_126, "[emts]_xiyou_0117_\r\n变猪猪\r\n#126[/emts]", false, 126,"[#126]",Emoji.EMOJI_GAME));
		map.put("#127", Emoji.fromResource(R.drawable.emotions_xiyou_127, "[emts]_xiyou_0118_\r\n乐极生悲\r\n#127[/emts]", false, 127,"[#127]",Emoji.EMOJI_GAME));
		map.put("#128", Emoji.fromResource(R.drawable.emotions_xiyou_128, "[emts]_xiyou_0119_\r\n捶地\r\n#128[/emts]", true, 128,"[#128]",Emoji.EMOJI_GAME));
		map.put("#129", Emoji.fromResource(R.drawable.emotions_xiyou_129, "[emts]_xiyou_0120_\r\n飘过\r\n#129[/emts]", true, 129,"[#129]",Emoji.EMOJI_GAME));
		map.put("#130", Emoji.fromResource(R.drawable.emotions_xiyou_130, "[emts]_xiyou_0121_\r\n恭喜发财\r\n#130[/emts]", true, 130,"[#130]",Emoji.EMOJI_GAME));
		map.put("#131", Emoji.fromResource(R.drawable.emotions_xiyou_131, "[emts]_xiyou_0122_\r\n虎虎生威\r\n#131[/emts]", true, 131,"[#131]",Emoji.EMOJI_GAME));
		map.put("#132", Emoji.fromResource(R.drawable.emotions_xiyou_132, "[emts]_xiyou_0123_\r\n不屑\r\n#132[/emts]", true, 132,"[#132]",Emoji.EMOJI_GAME));
		map.put("#133", Emoji.fromResource(R.drawable.emotions_xiyou_133, "[emts]_xiyou_0124_\r\n中箭\r\n#133[/emts]", true, 133,"[#133]",Emoji.EMOJI_GAME));
		map.put("#134", Emoji.fromResource(R.drawable.emotions_xiyou_134, "[emts]_xiyou_0125_\r\n亲近\r\n#134[/emts]", true, 134,"[#134]",Emoji.EMOJI_GAME));
		map.put("#135", Emoji.fromResource(R.drawable.emotions_xiyou_135, "[emts]_xiyou_0126_\r\n再见\r\n#135[/emts]", true, 135,"[#135]",Emoji.EMOJI_GAME));
		map.put("#136", Emoji.fromResource(R.drawable.emotions_xiyou_136, "[emts]_xiyou_0127_\r\n叹气\r\n#136[/emts]", true, 136,"[#136]",Emoji.EMOJI_GAME));
		map.put("#137", Emoji.fromResource(R.drawable.emotions_xiyou_137, "[emts]_xiyou_0128_\r\n吐舌头\r\n#137[/emts]", true, 137,"[#137]",Emoji.EMOJI_GAME));
		map.put("#138", Emoji.fromResource(R.drawable.emotions_xiyou_138, "[emts]_xiyou_0129_\r\n吓一条\r\n#138[/emts]", true, 138,"[#138]",Emoji.EMOJI_GAME));
		map.put("#139", Emoji.fromResource(R.drawable.emotions_xiyou_139, "[emts]_xiyou_0130_\r\n爱老虎油\r\n#139[/emts]", true, 139,"[#139]",Emoji.EMOJI_GAME));
		map.put("#140", Emoji.fromResource(R.drawable.emotions_xiyou_140, "[emts]_xiyou_0131_\r\n无聊\r\n#140[/emts]", true, 140,"[#140]",Emoji.EMOJI_GAME));
		map.put("#141", Emoji.fromResource(R.drawable.emotions_xiyou_141, "[emts]_xiyou_0132_\r\n晕\r\n#141[/emts]", false, 141,"[#141]",Emoji.EMOJI_GAME));
		map.put("#142", Emoji.fromResource(R.drawable.emotions_xiyou_142, "[emts]_xiyou_0133_\r\n有压力\r\n#142[/emts]", true, 142,"[#142]",Emoji.EMOJI_GAME));
		map.put("#143", Emoji.fromResource(R.drawable.emotions_xiyou_143, "[emts]_xiyou_0134_\r\n浮云\r\n#143[/emts]", true, 143,"[#143]",Emoji.EMOJI_GAME));
		map.put("#144", Emoji.fromResource(R.drawable.emotions_xiyou_144, "[emts]_xiyou_0135_\r\n神马\r\n#144[/emts]", true, 144,"[#144]",Emoji.EMOJI_GAME));
		map.put("#145", Emoji.fromResource(R.drawable.emotions_xiyou_145, "[emts]_xiyou_0136_\r\n给力\r\n#145[/emts]", true, 145,"[#145]",Emoji.EMOJI_GAME));
		map.put("#146", Emoji.fromResource(R.drawable.emotions_xiyou_146, "[emts]_xiyou_0137_\r\n老大\r\n#146[/emts]", true, 146,"[#146]",Emoji.EMOJI_GAME));
		map.put("#147", Emoji.fromResource(R.drawable.emotions_xiyou_147, "[emts]_xiyou_0138_\r\n麻匪\r\n#147[/emts]", true, 147,"[#147]",Emoji.EMOJI_GAME));
		map.put("#148", Emoji.fromResource(R.drawable.emotions_xiyou_148, "[emts]_xiyou_0139_\r\n可爱兔\r\n#148[/emts]", false, 148,"[#148]",Emoji.EMOJI_GAME));
		map.put("#149", Emoji.fromResource(R.drawable.emotions_xiyou_149, "[emts]_xiyou_0140_\r\n感动兔\r\n#149[/emts]", false, 149,"[#149]",Emoji.EMOJI_GAME));
		map.put("#150", Emoji.fromResource(R.drawable.emotions_xiyou_150, "[emts]_xiyou_0141_\r\n拍死\r\n#150[/emts]", true, 150,"[#150]",Emoji.EMOJI_GAME));
	}
	
	public static Drawable getSmileyDrawable(Context context,String id) {
		if(map.containsKey(id)) {
			Emoji emoji = map.get(id);
			Drawable drawable = context.getResources().getDrawable(emoji.resourceid);
			drawable.setBounds(0, 0, drawable.getIntrinsicWidth(), drawable.getIntrinsicHeight());
			return drawable;
		}
		return null;
	}
	
	public static Emoji getEmoji(String value) {
		Emoji emoji = map.get(value);
		
		return emoji;
	}
	
	public static Map<String, Emoji> smileyMap() {
		return map;
	}
	
	public static int smileySize() {
		return map.size();
	}
}
