/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_bruce_chatui_audio_Speex */

#ifndef _Included_com_bruce_chatui_audio_Speex
#define _Included_com_bruce_chatui_audio_Speex
#ifdef __cplusplus
extern "C" {
#endif
#undef com_bruce_chatui_audio_Speex_DEFAULT_COMPRESSION
#define com_bruce_chatui_audio_Speex_DEFAULT_COMPRESSION 4L
/*
 * Class:     com_bruce_chatui_audio_Speex
 * Method:    open
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_bruce_chatui_audio_Speex_open
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_bruce_chatui_audio_Speex
 * Method:    getFrameSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_bruce_chatui_audio_Speex_getFrameSize
  (JNIEnv *, jobject);

/*
 * Class:     com_bruce_chatui_audio_Speex
 * Method:    decode
 * Signature: ([B[SI)I
 */
JNIEXPORT jint JNICALL Java_com_bruce_chatui_audio_Speex_decode
  (JNIEnv *, jobject, jbyteArray, jshortArray, jint);

/*
 * Class:     com_bruce_chatui_audio_Speex
 * Method:    encode
 * Signature: ([SI[BI)I
 */
JNIEXPORT jint JNICALL Java_com_bruce_chatui_audio_Speex_encode
  (JNIEnv *, jobject, jshortArray, jint, jbyteArray, jint);

/*
 * Class:     com_bruce_chatui_audio_Speex
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_bruce_chatui_audio_Speex_close
  (JNIEnv *, jobject);

/*
 * Class:     com_bruce_chatui_audio_Speex
 * Method:    initEcho
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_bruce_chatui_audio_Speex_initEcho
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_bruce_chatui_audio_Speex
 * Method:    echoCancellation
 * Signature: ([S[S[S)V
 */
JNIEXPORT void JNICALL Java_com_bruce_chatui_audio_Speex_echoCancellation
  (JNIEnv *, jobject, jshortArray, jshortArray, jshortArray);

/*
 * Class:     com_bruce_chatui_audio_Speex
 * Method:    echoCancellationEncode
 * Signature: ([S[S[B)I
 */
JNIEXPORT jint JNICALL Java_com_bruce_chatui_audio_Speex_echoCancellationEncode
  (JNIEnv *, jobject, jshortArray, jshortArray, jbyteArray);

/*
 * Class:     com_bruce_chatui_audio_Speex
 * Method:    destroyEcho
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_bruce_chatui_audio_Speex_destroyEcho
  (JNIEnv *, jobject);

/*
 * Class:     com_bruce_chatui_audio_Speex
 * Method:    getAecStatus
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_bruce_chatui_audio_Speex_getAecStatus
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
